//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorMessageQueueServer.ServicioTienda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioTienda.ITienda")]
    public interface ITienda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITienda/RecibeSucamec", ReplyAction="http://tempuri.org/ITienda/RecibeSucamecResponse")]
        int RecibeSucamec(int intCodRegistro, int intEstado, string strFechaRespuesta, int intCodSucamec, string strNumeroLicencia, string strEstadoAntecedentePolicial, string strEstadoAntecedenteJudicial, string strEstadoAntecedentePenal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITiendaChannel : ConsumidorMessageQueueServer.ServicioTienda.ITienda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiendaClient : System.ServiceModel.ClientBase<ConsumidorMessageQueueServer.ServicioTienda.ITienda>, ConsumidorMessageQueueServer.ServicioTienda.ITienda {
        
        public TiendaClient() {
        }
        
        public TiendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RecibeSucamec(int intCodRegistro, int intEstado, string strFechaRespuesta, int intCodSucamec, string strNumeroLicencia, string strEstadoAntecedentePolicial, string strEstadoAntecedenteJudicial, string strEstadoAntecedentePenal) {
            return base.Channel.RecibeSucamec(intCodRegistro, intEstado, strFechaRespuesta, intCodSucamec, strNumeroLicencia, strEstadoAntecedentePolicial, strEstadoAntecedenteJudicial, strEstadoAntecedentePenal);
        }
    }
}
