//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSucamec.ServicioAntecedentes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAntecedentes.IAntecedentes")]
    public interface IAntecedentes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntecedentes/BuscarAntecedentes", ReplyAction="http://tempuri.org/IAntecedentes/BuscarAntecedentesResponse")]
        Entidades.EntidadAntecedente[] BuscarAntecedentes(string strDNI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAntecedentesChannel : WebSucamec.ServicioAntecedentes.IAntecedentes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AntecedentesClient : System.ServiceModel.ClientBase<WebSucamec.ServicioAntecedentes.IAntecedentes>, WebSucamec.ServicioAntecedentes.IAntecedentes {
        
        public AntecedentesClient() {
        }
        
        public AntecedentesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AntecedentesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AntecedentesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AntecedentesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.EntidadAntecedente[] BuscarAntecedentes(string strDNI) {
            return base.Channel.BuscarAntecedentes(strDNI);
        }
    }
}
